CREATE DATABASE DB_IMOB
USE DB_IMOB

CREATE TABLE TBL_CLIENTE_PESSOA_FISICA
(
	ID_CLIENTE INT PRIMARY KEY IDENTITY,
	FK_PESSOA_FISICA INT,
	STATUS_COMPRADOR VARCHAR(20),
	STATUS_LOCADOR VARCHAR(20),
	STATUS_LOCATORIO VARCHAR(20),
	STATUS_VENDEDOR VARCHAR(20)	
);


CREATE TABLE TBL_PESSOA_FISICA
(
	ID_PESSOA_FISICA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50),
	SOBRENOME VARCHAR(50),
	CPF VARCHAR(50),
	RG VARCHAR(50),
	DATA_NASCIMENTO DATE,
	SEXO CHAR,
	ESTADO_CIVIL VARCHAR(20),
	REGIME_BENS VARCHAR(20),
	NATURALIDADE VARCHAR(20),
	ESTADO_NATURALIDADE VARCHAR(20),
	ESCOLARIDADE VARCHAR(20),
	PROFISSAO VARCHAR(20),
	ANOTACOES VARCHAR(MAX),
	NOME_PAI VARCHAR(100),
	NOME_MAE VARCHAR(100),
	STATUS_CADASTRO INT
);

CREATE TABLE TBL_PESSOA_JURIDICA
(
	ID_PESSOA_JURIDICA INT PRIMARY KEY IDENTITY,
	FK_PESSOA_FISICA INT,
	RAZAO_SOCIAL VARCHAR(20),
	NOME_FANTASIA VARCHAR(20),
	CNPJ VARCHAR(20),
	INSCRICAO_ESTADUAL VARCHAR(20),
	INSENTO_INSCRICAO BIT,
	ATIVIDADE_PRINCIPAL VARCHAR(20),
	ATIVIDADES_SECUNDARIAS VARCHAR(100),
	DATA_ABERTURA_EMPRESA DATE,
	ANOTACOES VARCHAR(MAX),
	STATUS_CADASTRO BIT
);

CREATE TABLE TBL_CLIENTE_PESSOA_JURIDICA
(
	ID_CLIENTE_JURIDICA INT PRIMARY KEY IDENTITY,
	FK_PESSOA_JURIDICA INT,
	STATUS_COMPRADOR VARCHAR(20),
	STATUS_LOCADOR VARCHAR(20),
	STATUS_LOCATORIO VARCHAR(20),
	STATUS_VENDEDOR VARCHAR(20)	
);

CREATE TABLE TBL_AGENDAMENTO
(
	ID_AGENDAMENTO INT PRIMARY KEY IDENTITY,
	DATA_AGENDAMENTO DATE,
	HORA_AGENDAMENTO TIME,
	TIPO_AGENDAMENTO VARCHAR(20),
	ASSUNTO_AGENDAMENTO VARCHAR(20),
	ANOTACOES_AGENDAMENTO VARCHAR(MAX),
	STATUS_AGENDAMENTO INT,
	REAGENDAMENTO VARCHAR(10),
	DATA_REAGENDAMENTO DATE,
	HORA_REAGENDAMENTO TIME,
	FK_CLIENTE INT,
	FK_IMOVEL INT
);

CREATE TABLE AVISO
(
	ID_AVISO INT PRIMARY KEY IDENTITY,
	FK_CLIENTE INT,
	DATA_AVISO DATE,
	TIPO_AVISO VARCHAR(20),
	ASSUNTO_AVISO VARCHAR(20),
	MENSAGEM_AVISO VARCHAR(MAX),
	RESPOSTA_AVISO VARCHAR(MAX)
);

CREATE TABLE TBL_ENDERECO
(
	ID_ENDERECO INT PRIMARY KEY IDENTITY,
	TIPO_LOGRADOURO VARCHAR(50),
	LOGRADOURO VARCHAR(50),
	NUMERO_LOGRADOURO VARCHAR(50),
	COMPLEMENTO VARCHAR(50),
	CEP VARCHAR(9),
	LATITUDE FLOAT,
	LONGITUDE FLOAT,
	FK_CIDADE INT,
	NUMERO_APARTAMENTO INT,
	ANDAR_APARTAMENTO INT,
	BLOCO_APARTAMENTO INT
);

ALTER TABLE TBL_ENDERECO
ADD FK_IMOVEL INT, FK_PESSOA INT


CREATE TABLE TBL_CIDADES
(
	ID_CIDADE INT PRIMARY KEY IDENTITY,
	FK_ESTADO INT,
	NOME_CIDADE VARCHAR(50)
)

CREATE TABLE TBL_BAIRRO
(
	ID_BAIRRO INT PRIMARY KEY IDENTITY,
	NOME_BAIRRO VARCHAR(50),
	FK_CIDADE INT
)

CREATE TABLE TBL_ESTADOS
(
	ID_ESTADO INT PRIMARY KEY IDENTITY,
	NOME_ESTADO VARCHAR(50)
)


CREATE TABLE TBL_TELEFONES
(
	ID_TELEFONE INT PRIMARY KEY IDENTITY,
	FK_PESSOA INT,
	TIPO_TELEFONE INT,
	NUMERO_TELEFONE VARCHAR(50)
)

CREATE TABLE TBL_EMAILS
(
	ID_EMAIL INT PRIMARY KEY IDENTITY,
	FK_PESSOA INT,
	TIPO_EMAIL VARCHAR(50),
	EMAIL VARCHAR(50)
)

CREATE TABLE TBL_CORRETOR
(
	ID_CORRETOR INT PRIMARY KEY IDENTITY,
	ID_CODIGO_CORRETOR INT,
	FK_PESSOA_FISICA INT,
	NUMERO_CRECI INT
)

CREATE TABLE TBL_IMOVEL
(
	ID_IMOVEL INT PRIMARY KEY,
	STATUS_VENDA INT,
	NUMERO_MATRICULA VARCHAR(50),
	TIPO_IMOVEL VARCHAR(50),
	FOTOS VARCHAR(50),
	STATUS_LOCACAO VARCHAR(10),
	ANOTACOES VARCHAR(MAX),
	QUALIDADE_LOCALIZACAO VARCHAR (50),
	QUALIDADE_ACESSO VARCHAR(50)
);

CREATE TABLE TBL_IMOVEL_RURAL
(
	ID_IMOVEL_RURAL INT PRIMARY KEY IDENTITY,
	FK_IMOVEL INT,
	NUMERO_LTR VARCHAR(50),
	AREA_TOTAL VARCHAR(20),
	UNIDADE_AREA VARCHAR(20),
	AREA_APP VARCHAR(20),
	AREA_UTILIZAVEL VARCHAR(20),
	NUMERO_MATRICULA VARCHAR(20),
	TEM_CURRAL BIT,
	TEM_CASA_SEDE BIT,
	TEM_CASA_FUNCIONARIOS BIT,
	TEM_REPRESA BIT,
	TEM_RIO BIT
);

CREATE TABLE TBL_IMOVEL_URBANO
(
	ID_IMOVEL_URBANO INT PRIMARY KEY,
	FK_IMOVEL INT,
	NUMERO_IPTU INT,
	AREA_TOTAL INT,
	AREA_CONSTRUIDA INT,
	NUMERO_CONSTRUIDA VARCHAR(20),
	QTD_BANHEIROS INT,
	QTD_DORMITORIOS INT,
	QTD_SALAS INT,
	QTD_SUITES INT,
	TEM_GARAGEM BIT,
	TEM_EDICULA BIT,
	TEM_CHURRASQUEIRA BIT
);

CREATE TABLE TBL_PAGAMENTO_COMISSAO
(
	ID_PAGAMENTO_COMISSAO INT PRIMARY KEY IDENTITY,
	DATA_VENDA_LOCACAO DATE,
	DATA_PAGAMENTO DATE,
	FK_CORRETOR_IMOBILIARIO INT,
	FK_IMOBILIARIA INT,
	CODIGO_PAGADPR_COMISSAO INT,
	CONDICAO VARCHAR(20),
	ANOTACOES VARCHAR(20),
	STATUS VARCHAR(20),
	NUMERO_NOTA_RECIBO VARCHAR(20),
	DOCUMENTACAO_VENDA_LOCACAO VARCHAR(20)
)